image: registry.vela/velaluqa/gitlab-ci-build-images:ruby-2.3.3-phantomjs-2.1.1

cache:
  key: 'ruby233'
  paths:
    - vendor/ruby
    - node_modules

before_script:
  - bundle install -j $(nproc) --path vendor
  - npm install

stages:
  - deploy

run:
  stage: deploy
  script:
    - bundle exec rake test
    - bundle exec rake build
    - export PATH=$PATH:node_modules/.bin
    - bundle exec rake doc
    - bundle exec gitdeploy
